-- Refresh country-level Numbeo estimates.
-- averageSalaryEur = Average Monthly Net Salary (After Tax), EUR.
-- totalMonthlyCostEur = single person estimated monthly costs, excluding rent, EUR.

WITH numbeo_estimates(slug, salary, monthly_cost, source_url) AS (
  VALUES
    ('albania', 634, 610, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Albania'),
    ('andorra', 2587, 766, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Andorra'),
    ('armenia', 629, 609, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Armenia'),
    ('austria', 2604, 1062, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Austria'),
    ('azerbaidjan', 375, 454, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Azerbaijan'),
    ('belarus', 668, 492, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Belarus'),
    ('belgia', 2625, 960, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Belgium'),
    ('bosnia-si-hertegovina', 734, 588, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Bosnia%20And%20Herzegovina'),
    ('bulgaria', 1002, 610, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Bulgaria'),
    ('cehia', 1564, 778, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Czech%20Republic'),
    ('cipru', 1623, 851, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Cyprus'),
    ('croatia', 1370, 760, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Croatia'),
    ('danemarca', 3661, 1122, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Denmark'),
    ('estonia', 1650, 869, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Estonia'),
    ('finlanda', 2635, 1006, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Finland'),
    ('franta', 2455, 1003, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=France'),
    ('georgia', 482, 512, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Georgia'),
    ('germania', 2961, 998, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Germany'),
    ('grecia', 1021, 858, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Greece'),
    ('ungaria', 1213, 730, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Hungary'),
    ('islanda', 3953, 1230, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Iceland'),
    ('irlanda', 3064, 1105, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Ireland'),
    ('italia', 1685, 893, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Italy'),
    ('kosovo', 528, 460, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Kosovo%20(Disputed%20Territory)'),
    ('letonia', 1151, 788, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Latvia'),
    ('liechtenstein', 8462, 1400, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Liechtenstein'),
    ('lituania', 1385, 748, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Lithuania'),
    ('luxemburg', 4812, 1109, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Luxembourg'),
    ('malta', 1608, 910, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Malta'),
    ('moldova', 658, 490, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Moldova'),
    ('monaco', 8213, 1394, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Monaco'),
    ('muntenegru', 906, 608, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Montenegro'),
    ('macedonia-de-nord', 669, 507, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=North%20Macedonia'),
    ('tarile-de-jos', 3395, 1063, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Netherlands'),
    ('norvegia', 3602, 1110, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Norway'),
    ('polonia', 1492, 778, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Poland'),
    ('portugalia', 1153, 748, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Portugal'),
    ('romania', 920, 652, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Romania'),
    ('rusia', 843, 628, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Russia'),
    ('san-marino', 3452, 900, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=San%20Marino'),
    ('serbia', 839, 618, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Serbia'),
    ('slovacia', 1161, 778, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Slovakia'),
    ('slovenia', 1506, 831, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Slovenia'),
    ('spania', 1762, 775, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Spain'),
    ('suedia', 2838, 986, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Sweden'),
    ('elvetia', 6401, 1473, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Switzerland'),
    ('turcia', 706, 568, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Turkey'),
    ('ucraina', 424, 414, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Ukraine'),
    ('regatul-unit', 2927, 980, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=United%20Kingdom'),
    ('vatican', NULL, NULL, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Vatican%20City')
)
UPDATE countries
SET "averageSalaryEur" = numbeo_estimates.salary,
    "updatedAt" = now()
FROM numbeo_estimates
WHERE countries.slug = numbeo_estimates.slug;

WITH numbeo_estimates(slug, monthly_cost, source_url) AS (
  VALUES
    ('albania', 610, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Albania'),
    ('andorra', 766, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Andorra'),
    ('armenia', 609, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Armenia'),
    ('austria', 1062, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Austria'),
    ('azerbaidjan', 454, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Azerbaijan'),
    ('belarus', 492, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Belarus'),
    ('belgia', 960, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Belgium'),
    ('bosnia-si-hertegovina', 588, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Bosnia%20And%20Herzegovina'),
    ('bulgaria', 610, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Bulgaria'),
    ('cehia', 778, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Czech%20Republic'),
    ('cipru', 851, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Cyprus'),
    ('croatia', 760, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Croatia'),
    ('danemarca', 1122, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Denmark'),
    ('estonia', 869, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Estonia'),
    ('finlanda', 1006, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Finland'),
    ('franta', 1003, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=France'),
    ('georgia', 512, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Georgia'),
    ('germania', 998, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Germany'),
    ('grecia', 858, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Greece'),
    ('ungaria', 730, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Hungary'),
    ('islanda', 1230, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Iceland'),
    ('irlanda', 1105, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Ireland'),
    ('italia', 893, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Italy'),
    ('kosovo', 460, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Kosovo%20(Disputed%20Territory)'),
    ('letonia', 788, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Latvia'),
    ('liechtenstein', 1400, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Liechtenstein'),
    ('lituania', 748, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Lithuania'),
    ('luxemburg', 1109, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Luxembourg'),
    ('malta', 910, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Malta'),
    ('moldova', 490, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Moldova'),
    ('monaco', 1394, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Monaco'),
    ('muntenegru', 608, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Montenegro'),
    ('macedonia-de-nord', 507, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=North%20Macedonia'),
    ('tarile-de-jos', 1063, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Netherlands'),
    ('norvegia', 1110, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Norway'),
    ('polonia', 778, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Poland'),
    ('portugalia', 748, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Portugal'),
    ('romania', 652, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Romania'),
    ('rusia', 628, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Russia'),
    ('san-marino', 900, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=San%20Marino'),
    ('serbia', 618, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Serbia'),
    ('slovacia', 778, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Slovakia'),
    ('slovenia', 831, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Slovenia'),
    ('spania', 775, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Spain'),
    ('suedia', 986, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Sweden'),
    ('elvetia', 1473, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Switzerland'),
    ('turcia', 568, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Turkey'),
    ('ucraina', 414, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Ukraine'),
    ('regatul-unit', 980, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=United%20Kingdom'),
    ('vatican', NULL, 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Vatican%20City')
)
UPDATE cost_of_living
SET "totalMonthlyCostEur" = numbeo_estimates.monthly_cost,
    "sourceName" = 'Numbeo - cost lunar fără chirie și salariu net',
    "sourceUrl" = numbeo_estimates.source_url,
    "collectedAt" = DATE '2026-05-30',
    "updatedAt" = now()
FROM countries, numbeo_estimates
WHERE cost_of_living."countryId" = countries.id
  AND cost_of_living."cityId" IS NULL
  AND countries.slug = numbeo_estimates.slug;
